blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/igordcard/straat/wiki
    about: Visit the project wiki for documentation (once available)
  - name: 💬 Community Support
    url: https://github.com/igordcard/straat/discussions
    about: Join community discussions for general questions and support
